---
# tasks file for roles/changemotd

- name: Message of the day
  copy:
    content: "Welcome and Mabuhay!\n"
    dest: "/etc/motd"

- name: Disable default motd
  file:
    dest: "/etc/update-motd.d/"
    mode: 1666
    state: directory
    recurse: yes
