---
# tasks file for roles/python

- name: Install Python3 and pip3 
  apt:
    name:
      - python3
      - python3-pip
    state: latest
    update_cache: yes

- name: pip3 as default pip
  shell: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

- name: python3 as default python
  shell: update-alternatives --install /usr/bin/python python /usr/bin/python3 10
